#!/usr/bin/bash

export LC_COLLATE=C
shopt -s extglob
while true; do
	choice=$(zenity --list \
		--column "Choose your option" \
		CreateTable \
		ListTables \
		InsertTable \
		UpdateTable \
		DeleteTable \
		SelectFromTable \
		DropTable \
		Back)

	#select choice in CreateTable ListTables InsertTable UpdateTable DeleteTable SelectFromTable DropTable Back; do

	case $choice in
	CreateTable)
		~/TEST/testCreateTable.sh
		;;
	ListTables)
		zenity --info \
			--title "Tables" \
			--width 500 \
			--height 100 \
			--text "$(ls -l)"
		#   ls -l
		;;
	InsertTable)
		~/TEST/testInsertTable.sh
		;;
	UpdateTable)
		~/TEST/testUpdateTable
		;;
	DeleteTable)
		~/TEST/testDeleteRecord.sh
		;;
	SelectFromTable)
		~/TEST/testSelectFromTable.sh
		;;
	DropTable)
		~/TEST/testDropTable.sh
		;;
	Back)
		break
		;;
	*)
		zenity --error \
			--title "Not Found" \
			--width 500 \
			--height 100 \
			--text "Wrong Input"
		# echo "Wrong Input"
		;;
	esac
	#echo '1)CreateTable       2)ListTables       3)InsertTable       4)UpdateTable       5)DeleteTable       6)SelectFromTable       7)DropTable       8)Back'
done

