#!/usr/bin/bash

export LC_COLLATE=C
shopt -s extglob
while true; do
	choice=$(zenity --list \
		--column "Choose your option" \
		--width 500 \
		--height 300 CreateTable \
		ListTables \
		InsertTable \
		UpdateTable \
		DeleteTable \
		SelectFromTable \
		DropTable \
		Back)

	case $choice in
	CreateTable)
		~/DBMS_BASH_GUI/testCreateTable.sh
		;;
	ListTables)
		zenity --info \
			--title "Tables" \
			--width 500 \
			--height 300 \
			--text "$(ls -l)"
		;;
	InsertTable)
		~/DBMS_BASH_GUI/testInsertTable.sh
		;;
	UpdateTable)
		~/DBMS_BASH_GUI/testUpdateTable
		;;
	DeleteTable)
		~/DBMS_BASH_GUI/testDeleteRecord.sh
		;;
	SelectFromTable)
		~/DBMS_BASH_GUI/testSelectFromTable.sh
		;;
	DropTable)
		~/DBMS_BASH_GUI/testDropTable.sh
		;;
	Back)
		break
		;;
	*)
		break
		;;
	esac
done
